### ISSUE TITLE
Error when attempting to use example jsonpath value from Customizing LAMS Match Examples section

### ISSUE THREAD

**Issue by tkovich** [looker-open-source/look-at-me-sideways#115] opened 2023-01-06 00:47 UTC
Hi Fabio!

Sorry to hit you with two at once haha -- one other thing I noticed using the Rule Sandbox and the Customizing LAMS page. I get an error when I try to use the "match" JSONpath "$.model.*.view.*['dimension','measure'].*", which is one of the examples given [here](https://looker-open-source.github.io/look-at-me-sideways/customizing-lams#match-examples).

![image](https://user-images.githubusercontent.com/25917575/210907299-423c750a-5f82-453a-80f7-6b148194c843.png)

Error text: ❌ Invalid jsonpath in manifest/rule:sandbox_rule/match: $.model.*.view.*['dimension','measure'].*

I tried a few variations, but can't find a syntax that will work to get me all dimensions + measures. Each of these work individually:

`$.model.*.view.*.dimension.*
$.model.*.view.*.measure.*
$.model.*.view.*.dimension_group.*
`

... but I can't find a syntax that would allow me to return all dimensions AND all measures, or all dimensions AND all dimension_groups.

Hoping there's a syntax that will do that, but if not, wanted to let. you know so you could remove that example from. the Customizing LAMS page. (Or maybe it's something I'm doing wrong, or a problem with the sandbox -- admittedly I haven't tried it  except in the sandbox.)

Thanks again!

Teresa Kovich
Principal Consultant, DAS42

**Comment by fabio-looker** [comment] 2023-01-13 17:00
Hi Teresa,

This measures & dimensions use case not working has been mentioned to me on a couple of occasions, but I haven't had any success pinpointing the root cause... I suspect there might be a bug around this kind of jsonpath in the underlying library we use. I haven't prioritized it yet since both people that reported it ended up working around it with a second copied rule...

I'll leave this open as a bug and see if I can do some more investigation.

Fabio

**Comment by fabio-looker** [comment] 2023-03-27 04:49
This should be resolved in the v3 beta release: https://www.npmjs.com/package/@looker/look-at-me-sideways/v/3.0.0-beta.0

Release notes: https://github.com/looker-open-source/look-at-me-sideways/blob/fabble/v3-extends-refinements/docs/release-notes/v3.md

Any feedback is welcome and may be incorporated into the v3 release!

**Comment by fabio-looker** [comment] 2023-05-13 04:58
Hello!

Although this issue was handled in 3.0.0-beta.0 , that beta release had several other issues. Many of those issues are fixed in the next beta pre-release [3.0.0-beta.1](https://www.npmjs.com/package/@looker/look-at-me-sideways/v/3.0.0-beta.1).

[v3 release notes](https://github.com/looker-open-source/look-at-me-sideways/blob/fabble/v3-extends-refinements/docs/release-notes/v3.md)

I'll keep this issue open until v3 is out of beta. Thank you for your feedback thus far, and any further feedback is welcome!

**Comment by fabio-looker** [comment] 2023-06-06 23:28
Hi @tkovich 

[v3](https://looker-open-source.github.io/look-at-me-sideways/release-notes/v3) is now generally available, and uses a new JSONPath library that should resolve this issue.

I'm closing out this issue, but if you run into any issues, please let me know and I can re-open it!

**Closed by fabio-looker** 2023-06-06 23:28 UTC
