### ISSUE TITLE
LAMS Erroring

### ISSUE THREAD

**Issue by alec-flatiron** [looker-open-source/look-at-me-sideways#58] opened 2022-01-28 17:02 UTC
@fabio-looker - apologies for a somewhat direct message here, but I've spent some time digging here and can't seem to find what's going / don't have the relevant expertise. Our last successful lint was 8 days ago (1/20), our next run wasn't until 1/26, but that run and all subsequent have failed with an error that looks like the one below.

I didn't see any new recent lams commits, but based on the error I suspected some issue with the the Object's value's not being available, which I thought might be parser related. I see a commit 7 days ago in lookml-parser. It looks harmless. I re-installed lams locally and confirmed the same error was occurring with a fresh install. I downloaded lookml-parser@6.4.0 and replaced the contents of the lams lookml-parser directory locally (which had 6.4.1) with the 6.4.0 contents. Unfortunately, this didn't solve the problem. I tried 6.3.0 as well, and rather than an error in F1, it passed through to K1-2-3-4 until erroring with a similar issue.

I'm not quite sure where to go from here, but things seem a bit broken. We rely on some custom lint rules so I hope you can point me in the right direction!

Fresh lams install and 6.4.0 parser error:
![image](https://user-images.githubusercontent.com/98607855/151589966-e72eba1c-9cfc-403a-860d-0ee6e8d2cf25.png)

6.3.0 parser error:
![image](https://user-images.githubusercontent.com/98607855/151589921-247ee7e5-8171-4ffe-9e2e-144eecc9fa06.png)

**Comment by fabio-looker** [comment] 2022-01-28 17:27
Hi! Sorry for this - I have been making changes to the parser and LAMS recently, so I'm sorry that it seems I inadvertently broke something. I'm not sure why it might have broken though if you didn't pull the latest version of LAMS. What LAMS version are you running?

I can either try to publish a patch version that still uses the older release of the parser, or if you want you could try using the new version of LAMS that I published, but that the docs are still WIP.

To use the new LAMS version, v2.0.1, make sure to add in the following parameter: `--output=markdown` for the prior functionality of outputting an issues.md file, or `-output=lines` for a newer line-by-line human-readable output to the CLI

**Comment by alec-flatiron** [comment] 2022-01-28 17:43
@fabio-looker - Sorry, to clarify, I believe both of the errors below are using LAMS v2.0.1. I ran a fresh `npm install -g @looker/look-at-me-sideways`  before messing around with the `lookml-parser` dependency (and I see 2.0.1 in package.json)

**Comment by fabio-looker** [comment] 2022-01-28 17:51
Thanks for clarifying! The stack trace in your error message looks pretty specific, so I'll review today to see if I can find the error quickly.

**Comment by alec-flatiron** [comment] 2022-01-31 21:33
@fabio-looker If you get a chance to look at this this week let me know! Seems like older versions may be fine so I can pin to that, but not sure if that's necessary

**Comment by fabio-looker** [comment] 2022-02-01 17:29
@alec-flatiron I took a quick look and where the issue is in LAMS, I'm actually surprised it was working previously. I will have to go into the parser to fix this... although I am aiming for this week, I think pinning to v1 is not a bad idea in general until this case is tested, fixed, and working for you

**Comment by vpipkt** [comment] 2022-02-04 09:13
Same issue here. Our builds started breaking right when 2.0.0 was released to npm. In our github actions we are now using:

` run: npx @looker/look-at-me-sideways@1.6.1 ...`

**Comment by fabio-looker** [comment] 2022-02-14 19:33
v2.0.2 published to NPM should resolve this bug, but since v2 does include changes to the default output settings, I still recommend people pin their configurations to v1 until they are ready to explicitly update to v2. I am working on the release notes for that still.

**Comment by alec-flatiron** [comment] 2022-02-14 21:39
@fabio-looker Getting some fresh errors with 2.0.2 but these are more clear. The rest of the errors look like valid errors according to the rules, but some look like included test cases? Also, will a valid run still spit out "BUILD PASSED"?

`❌       P0..... r/test-projects/007-lookml-maps/facts.view.lkml Parsing error: Object.fromEntries is not a function
❌       P1..... rnal_use/adjustment_pdt_restricted.explore.lkml Parsing error: Expected "#", "\"", [ \t\n\r], or [\-+_a-zA-Z0-9.] but "]" found.`

**Comment by fabio-looker** [comment] 2022-02-15 22:30
Hi @alec-flatiron - thanks for passing this info along. This separate error is already reported in issue #61. I'll be fixing that one next/shortly. (My apologies again that these were not caught by our test suite). I'm leaving this ticket open just in case until all the errors are confirmed resolved.

**Comment by fabio-looker** [comment] 2022-02-22 20:21
Thanks to everyone for bearing with me.

- Both the runtime error and reported parsing issues should be fixed in [v2.0.3](https://www.npmjs.com/package/@looker/look-at-me-sideways/v/2.0.3)
- **The default output format is different from v1, so even with these bugfixes v2 is not a drop-in replacement for v1**
- Docs have been updated with [an article about the contents of the v2 release](https://looker-open-source.github.io/look-at-me-sideways/release-notes/v2)
- To prevent similar issues in the future, I have updated any installation docs that install from NPM to include an explicit reference a major version in the installation command, and added tests to ensure these docs remain in-sync with the currently published major version.

If you still exprience any unexpected errors, let me know and I will re-open the ticket.

**Closed by fabio-looker** 2022-02-22 20:21 UTC
