### ISSUE TITLE
Error setting up github action 

### ISSUE THREAD

**Issue by juantorrezwm** [looker-open-source/look-at-me-sideways#124] opened 2023-02-24 18:44 UTC
Hi, I'm trying to create the gihub action to use LAMS in my CI.

When I run a commit in Looker IDE I get this error:

![image](https://user-images.githubusercontent.com/89479471/221263979-31999d28-b0f6-4487-b952-f90194cb97ff.png)

This is my current workflow file:

name: CI

on: [push]

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
    - name: Checkout your LookML
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install LAMS
      run: npm install -g @looker/look-at-me-sideways@2
    - name: Run LAMS
      run: lams --reporting=save-yes

I can't see the error on the log file just **"Error: Process completed with exit code 1."** It seems the rule validation is ok, but something happen at the end of the code.

Could you help me with this? Do I need some specific configuration on my github branch besides github actions to use LAMS?
Thanks.

Thanks.

**Comment by fabio-looker** [comment] 2023-02-24 19:12
Hi @juantorrezwm 

This seems to be working as intended. Because there are things about your project that violate some built-in LAMS linter rules (specifically, all those rows with the red X's), the process will error to indicate to Github Actions that the commit should not be approved.

If there are certain rules that do not wish to comply with, you can add rule_exemptions to your manifest.lkml. ( See [customizing LAMS](https://looker-open-source.github.io/look-at-me-sideways/customizing-lams.html) for details)

**Comment by juantorrezwm** [comment] 2023-02-24 19:22
Got It, so if I fix the LAMS errors on my code, I wouldn't get that "Error: Process completed with exit code 1"

But it happens to me that even when I have the errors on the log, Looker allows me to commit the changes in production. From what I understood, Looker should not allow me to deploy if there are any errors and It should show me the errors to be corrected in the Looker IDE. I am right?

I thought that it did not show me the errors in looker because of that error, but I see that it is not like that.

**Comment by fabio-looker** [comment] 2023-02-24 19:37
On the Looker side, you should configure Looker to require pull requests: https://cloud.google.com/looker/docs/git-options#integrating_pull_requests_for_your_project

Then on the github side, you should protect your `main` branch, requiring status checks to pass before merging PRs: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

or at least that is the configuration I am aware of, there may be other options

**Comment by fabio-looker** [comment] 2023-03-24 06:35
It seems the linter is working as expected, so I am closing this out, but if you still have any problems, feel free to comment back.

**Closed by fabio-looker** 2023-03-24 06:35 UTC
Labels: support
