### ISSUE TITLE
Commit works smooth even if there are errors in issues.md

### ISSUE THREAD

**Issue by shreyabnsl09** [looker-open-source/look-at-me-sideways#93] opened 2022-05-25 09:09 UTC
I'm trying to integrate LAMS with Looker using Gitlab. Created 'Gitlab-ci.yml' file and pipeline is running. Can see 'issues.md' file in pipeline job artifacts.
My concern is even if I have errors in my issues.md file, 'commit changes' from Looker works smooth. Shouldn't the commit fail since there are errors in issues.md file?

Objective : Developer shouldn't be able to commit their changes if there are errors in issues.md file. (Issues.md file is available in job artifacts)

**Comment by fabio-looker** [comment] 2022-05-25 15:28
Hi @shreyabnsl09 

It depends on which version of LAMS you are using, and how you have configured your CI process.

Note that between v1 and v2, the default output mode of LAMS changed, from the issues.md file to stdout/command-line output. However, the deployment example for Gitlab CI is still for v1, as I don't use Gitlab and depend on the community to help maintain that deployment example (see https://github.com/looker-open-source/look-at-me-sideways/issues/91 )

Can you confirm what version of LAMS you are running and what your CI configuration looks like?

**Comment by shreyabnsl09** [comment] 2022-05-26 09:31
@fabio-looker Thanks for your response.
This is my gitlab-ci.yml file. I am using docker image from docker hub.
<img width="663" alt="gitlab-ci" src="https://user-images.githubusercontent.com/103121421/170460570-166ea0a6-ee64-4fbe-be9f-eb14c3276642.PNG">

**Comment by shreyabnsl09** [comment] 2022-05-26 12:17
@[PieterjanCriel](https://github.com/PieterjanCriel)
Any suggestions on this?

**Comment by shreyabnsl09** [comment] 2022-05-27 11:40
@fabio-looker Any suggestions on this?
I tried with LAMS V2 as well. Still experiencing the same behavior.

**Comment by fabio-looker** [comment] 2022-05-27 15:32
From the contributed example, it's not clear to me whether its intended effect is to prevent some action entirely, or to merely provide the findings in an artifacts for a reviewer's use. Other than that possibly incorrect observation, I really don't know how Gitlab CI expects things to be configured.

Also, if the linter is running in CI (which is a separate machine from the developer), that kind of implies the code has already been committed. You could prevent the code from being merged, but it's too late to prevent it from being committed. For that, you would probably need something like https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks , however that is for situations where developers are writing the LookML on their own computers and willing to setup a dev environment with Node.js and the linter

**Comment by fabio-looker** [comment] 2022-10-17 07:28
Closing as duplicate of #91

**Closed** 2022-10-17 07:28 UTC
